---
# tasks file for hswong3i.ganesha

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.ganesha

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  tags: hswong3i.ganesha

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  notify: restart ganesha
  tags: hswong3i.ganesha

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/nfs-ganesha.j2", dest: "/etc/init.d/nfs-ganesha", owner: "root", group: "root", mode: "0755" }
  notify: restart ganesha
  tags: hswong3i.ganesha

- name: enable service
  service:
    name: "rpcbind"
    state: "started"
    enabled: "yes"
  notify: restart ganesha
  tags: hswong3i.ganesha

- name: enable service
  service:
    name: "nfs-ganesha"
    enabled: "yes"
  notify: restart ganesha
  tags: hswong3i.ganesha
