---
# handlers file for hswong3i.ganesha

- name: restart ganesha (trusty)
  service:
    name: "nfs-ganesha"
    state: "restarted"
  when: "{{ ansible_distribution_release == 'trusty' }}"

- name: restart ganesha (xenial)
  systemd:
    name: "nfs-ganesha.service"
    state: "restarted"
  when: "{{ ansible_distribution_release == 'xenial' }}"
